/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function GraduationHat(props) {
  const { nodes, materials } = useGLTF('models/prop 3D_FINAL.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials['Material.016']}
        position={[0.06218, 0, -0.6209574]}
        rotation={[0, 0, Math.PI]}
        scale={1.2520689}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials['Material.016']}
        position={[-0.0004776, 0.0000192, -0.7869369]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials['Material.002']}
        position={[0.6561392, 1.0858902, -0.5808724]}
        rotation={[0, 0, -Math.PI]}
        scale={[-0.1568532, -0.0262811, -0.0232965]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials['Material.001']}
        position={[0.7301353, 1.0208459, -0.5392697]}
        rotation={[Math.PI, -Math.PI / 4, Math.PI]}
        scale={[0.1296651, 0.0326588, 0.1296651]}
      />
      <group
        position={[0.7364423, 1.0127614, -0.3018653]}
        rotation={[-Math.PI, -Math.PI / 4, -Math.PI / 2]}
        scale={[0.0262811, 0.0389365, 0.0389365]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BezierCurve_1.geometry}
          material={materials['Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BezierCurve_2.geometry}
          material={materials['Material.003']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('models/prop 3D_FINAL.glb')
